apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-project-blue
  labels:
    app: udacity-capstone-project

spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone-project
      version: blue
  template:
    metadata:
      labels:
        app: udacity-capstone-project
        version: blue
    spec:
      containers:
        - name: udacity-capstone-project
          image: docker.io/geekahmed/udacity-devops-capstone-blue
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "1000m"

