apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-project-green
  labels:
    app: udacity-capstone-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-capstone-project
      version: green
  template:
    metadata:
      labels:
        app: udacity-capstone-project
        version: green
    spec:
      containers:
        - name: udacity-capstone-project
          image: docker.io/geekahmed/udacity-devops-capstone-green
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"

